<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.


/**
 * Strings for component 'paygw_flouci', language 'en'.
 *
 * @package    paygw_flouci
 * @copyright  2026 Your Organisation
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$string['amount'] = 'Amount';
$string['apierror'] = 'The payment service (Flouci) could not be reached or returned an unexpected answer. Please try again in a few minutes.';
$string['cannotstart'] = 'The payment could not be started. Your account has not been debited. Please try again or contact the site administrator.';
$string['checkagain'] = 'Check again';
$string['deliverypending'] = 'Your payment has been received. Your purchase is being finalised and will be available in a moment.';
$string['event_payment_completed'] = 'Flouci payment completed';
$string['event_payment_mismatch'] = 'Flouci payment mismatch';
$string['flouciid'] = 'Flouci payment ID';
$string['gatewaydescription'] = 'Flouci lets you pay in Tunisian dinars with your Flouci wallet or a bank card.';
$string['gatewayname'] = 'Flouci';
$string['id'] = 'ID';
$string['invalidamount'] = 'The amount to pay is not valid.';
$string['invalidkey'] = 'The key must not contain spaces or colons.';
$string['item'] = 'Item (component / area / id)';
$string['lasterror'] = 'Last message';
$string['lockfailed'] = 'The payment is being processed by another request. Please try again in a moment.';
$string['mismatchesfound'] = '{$a} Flouci payment(s) were flagged because the amount or reference reported by Flouci does not match what was requested. The order was not delivered. Please review them and refund or fix manually.';
$string['notconfigured'] = 'The Flouci payment gateway is not configured for this payment account.';
$string['notransactions'] = 'No Flouci payment sessions found.';
$string['paymentexpired'] = 'The payment session expired and you were not charged. You can try again.';
$string['paymentfailed'] = 'The payment was not completed and you were not charged. You can try again.';
$string['paymentmismatch'] = 'We could not match your payment with the amount due, so your purchase has not been delivered yet. Please contact the site administrator and quote reference {$a}.';
$string['paymentpending'] = 'Your payment has not been confirmed yet. If you completed it, please wait a few seconds and check again. Your purchase will be delivered automatically as soon as Flouci confirms the payment.';
$string['paymentsuccessful'] = 'Payment received. Thank you!';
$string['pluginname'] = 'Flouci';
$string['pluginname_desc'] = 'The Flouci plugin lets you receive payments in Tunisian dinars (TND) through Flouci. Create an application in your Flouci developer account, then enter its public and private keys in the Flouci section of a payment account (Site administration > Payments > Payment accounts). Use the keys of the TEST APP while testing, then your production keys.';
$string['privacy:metadata:flouci'] = 'To process the payment, an amount and an opaque random reference are sent to Flouci. The customer then enters their payment details on the Flouci site; Moodle never sees or stores them.';
$string['privacy:metadata:flouci:amount'] = 'The amount to pay, in millimes.';
$string['privacy:metadata:flouci:trackingid'] = 'A random reference generated by Moodle. It does not contain any personal data.';
$string['privacy:metadata:paygw_flouci'] = 'Stores the state of each Flouci payment session.';
$string['privacy:metadata:paygw_flouci:amountmillimes'] = 'The amount charged, in millimes.';
$string['privacy:metadata:paygw_flouci:flouciid'] = 'The payment ID assigned by Flouci.';
$string['privacy:metadata:paygw_flouci:item'] = 'What the user paid for.';
$string['privacy:metadata:paygw_flouci:ref'] = 'The random reference of the payment session.';
$string['privacy:metadata:paygw_flouci:status'] = 'The state of the payment session.';
$string['privacy:metadata:paygw_flouci:time'] = 'When the payment session was created.';
$string['privacy:metadata:paygw_flouci:userid'] = 'The ID of the user who started the payment.';
$string['publickey'] = 'Public key (APP_PUBLIC)';
$string['publickey_help'] = 'The public key of your application, from the Flouci developer dashboard. Use the TEST APP keys for testing and your production keys when you go live.';
$string['redirecting'] = 'Redirecting to Flouci...';
$string['secretkey'] = 'Private key (APP_SECRET)';
$string['secretkey_help'] = 'The private key of your application, from the Flouci developer dashboard. Keep it secret.';
$string['status_complete'] = 'Complete';
$string['status_expired'] = 'Expired';
$string['status_failed'] = 'Failed';
$string['status_mismatch'] = 'Mismatch (review)';
$string['status_paid'] = 'Paid, delivery pending';
$string['status_pending'] = 'Pending';
$string['task_cleanup'] = 'Flouci: clean up old payment sessions';
$string['task_reconcile'] = 'Flouci: reconcile pending payments';
$string['transactionnotfound'] = 'Payment session not found.';
$string['transactions'] = 'Flouci transactions';
$string['unsupportedcurrency'] = 'Flouci only supports payments in TND, but this item is priced in {$a}.';
